YEAR:
  dtype: INT
MONTH:
  dtype: INT
DAY:
  dtype: INT
DAY_OF_WEEK:
  dtype: INT
AIRLINE:
  dtype: VARCHAR
FLIGHT_NUMBER:
  dtype: INT
TAIL_NUMBER:
  dtype: VARCHAR
ORIGIN_AIRPORT:
  dtype: VARCHAR
DESTINATION_AIRPORT:
  dtype: VARCHAR
SCHEDULED_DEPARTURE:
  dtype: INT
DEPARTURE_TIME:
  dtype: INT
DEPARTURE_DELAY:
  dtype: INT
TAXI_OUT:
  dtype: INT
WHEELS_OFF:
  dtype: INT
SCHEDULED_TIME:
  dtype: INT
ELAPSED_TIME:
  dtype: INT
AIR_TIME:
  dtype: INT
DISTANCE:
  dtype: INT
WHEELS_ON:
  dtype: INT
TAXI_IN:
  dtype: INT
SCHEDULED_ARRIVAL:
  dtype: INT
ARRIVAL_TIME:
  dtype: INT
ARRIVAL_DELAY:
  dtype: INT
DIVERTED:
  dtype: INT
CANCELLED:
  dtype: INT
CANCELLATION_REASON:
  dtype: VARCHAR
AIR_SYSTEM_DELAY:
  dtype: INT
SECURITY_DELAY:
  dtype: INT
AIRLINE_DELAY:
  dtype: INT
LATE_AIRCRAFT_DELAY:
  dtype: INT
WEATHER_DELAY:
  dtype: INT
